language: haskell
install:
  - nvm install 0.12
  - cabal install elm-make
  - cabal install elm-package
script: make init && make test
notifications:
  email:
    - gunpinyo@gmail.com
  on_success: always
  on_failure: always
