language: haskell
install:
  - nvm install 0.12
  - cabal install elm-make
  - cabal install elm-package
  - make init
script: make test
notifications:
  email:
    - gunpinyo@gmail.com
  on_success: always
  on_failure: always
