language: haskell
install:
  - npm install -g elm@0.16.0
  - elm-package install -y
before_script:
  - bash scripts/gen-tests.sh
script: node tests.js
notifications:
  email:
    - gunpinyo@gmail.com
  on_success: always
  on_failure: always
